<?php
/**
 * Created by PhpStorm.
 * User: Ryuji Ogasawara
 * Date: 2016/10/03
 * Time: 午後7:02
 */

namespace Autodesk\Forge\PHP\Sample;

use Autodesk\Forge\PHP\Sample\Core\Application;

require_once 'core/Application.php';

class BasicApplication extends Application
{
    public function getRootDir()
    {
        return dirname(__FILE__);
    }
    
    protected function registerRoutes()
    {
        return array(
        '/'
        => array('controller' => 'main', 'action' => 'index'),
        '/login'
        => array('controller' => 'main', 'action' => 'login'),
        '/logout'
        => array('controller' => 'main', 'action' => 'logout'),
        '/oauth/callback'
        => array('controller' => 'main', 'action' => 'getAccessToken'),
        '/userprofile'
        => array('controller' => 'main', 'action' => 'getUserProfile'),
        '/hub'
        => array('controller' => 'main', 'action' => 'getHub'),
        '/user/:user_name'
        => array('controller' => 'status', 'action' => 'user'),
        '/user/:user_name/status/:id'
        => array('controller' => 'status', 'action' => 'show'),
        '/account'
        => array('controller' => 'account', 'action' => 'index'),
        '/account/:action'
        => array('controller' => 'account'),
        '/follow'
        => array('controller' => 'account', 'action' => 'follow')
        );

    }
    
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }
}